export const mails = [
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
	{
		id: "TASK-8782",
		email: "example@gmail.com",
		subscriptionDate: "2033-23-23",
		subscriberName: "Elvis Ndubuisi",
		group: ["medium", "works"],
	},
];