import { type Metadata } from "next";
import DashboardMenu from "../_components/dashboard-menu";
import { Separator } from "../_components/ui/separator";
import Sidebar from "../_components/sidebar";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ULayout({ children }: { children: React.ReactNode }) {
	return (
		<main>
			<DashboardMenu />
			<Separator />
			<section className='mx-auto flex h-[92vh] max-w-screen-2xl flex-row px-4 md:px-3'>
				<Sidebar />
				<Separator orientation='vertical' />
				{children}
			</section>
		</main>
	);
}
