import { geist } from "@/app/lib/font";
import { type Metadata } from "next";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ULayout({ children }: { children: React.ReactNode }) {
	return (
		<main className={geist.className}>
			<h1>U layout</h1>
			<>{children}</>
		</main>
	);
}
