import "~/styles/globals.css";

import { Inter, Figtree } from "next/font/google";
import { cookies } from "next/headers";
import { ThemeProvider } from "./_context/theme-provider";
import { Toaster } from "./_components/ui/toaster";

import { TRPCReactProvider } from "~/trpc/react";

const figtree = Figtree({
	subsets: ["latin"],
});

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${figtree.className}`}>
				<TRPCReactProvider cookies={cookies().toString()}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
						<Toaster />
					</ThemeProvider>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
