import "@/styles/global.css";

import { geist, geistMono } from "@/app/lib/font";
import { headers } from "next/headers";
import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "./_context/theme-provider";
import { AuthSessionProvider } from "./_context/auth-session-provider";

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${geist.variable} ${geistMono.variable} font-sans`}>
				<AuthSessionProvider>
					<TRPCReactProvider headers={headers()}>
						<ThemeProvider
							attribute='class'
							defaultTheme='system'
							enableSystem
							disableTransitionOnChange>
							{children}
						</ThemeProvider>
					</TRPCReactProvider>
				</AuthSessionProvider>
			</body>
		</html>
	);
}
